vm_arguments:

  # GENERAL
  - argument:
      name: node_name
      description: Name of the node
      value: -name nonode@nohost

  - argument:
      name: cookie
      description: Erlang cookie
      value: -setcookie veil_cluster_node

  - argument:
      name: error_logger_warnings
      description: Treat error_logger warnings as warnings
      value: +W w

  - argument:
      name: erl_max_ports
      description: Increase number of concurrent ports/sockets
      value: -env ERL_MAX_PORTS 4096



veil_cluster_node_env:

  # GENERAL
  - parameter:
      name: node_type
      description: Node type (worker or ccm)
      value: ccm

  - parameter:
      name: ccm_nodes
      description: List of possible ccm nodes
      value: |
        ["\'ccm1@127.0.0.1\'"]
      erlang_term: |
        ['ccm1@127.0.0.1']

  - parameter:
      name: db_nodes
      description: List of all DBMS nodes
      value: |
        ["\'db1@127.0.0.1\'"]
      erlang_term: |
        ['db1@127.0.0.1']

  - parameter:
      name: initialization_time
      description: How long should ccm wait for workers before it initializes cluster
      value: 10

  - parameter:
      name: heart_beat
      description: How long (in sec) should worker sleep before next connection try (when it cannot connect to ccm)
      value: 60

  - parameter:
      name: cluster_clontrol_period
      description: How long (in sec) should ccm wait between successive checks of cluster status
      value: 60

  - parameter:
      name: worker_load_memory_size
      description: Memory size which stores information about worker load
      value: 1000

  - parameter:
      name: hot_swapping_time
      description: |
        Time in ms after witch code of loops will be reloaded
        e.g. if value is 10000 hot_swap message will be sent to loops 10 seconds after release_handler:install_release execution
      value: 2000

  - parameter:
      name: ssl_cert_path
      description: Path to certificate used by ranch_ssl
      value: |
        "\'./cacerts/veilfs.pem\'"
      erlang_term: "'./cacerts/veilfs.pem'"
      # this has to be in double quotes so that single quotes are preserved after
      # conversion to list and it ends up correct in app.src

  - parameter:
      name: fslogic_cleaning_period
      description: How often fslogic should clean not used descriptors
      value: 600

  - parameter:
      name: node_monitoring_period
      description: How often should node manager wait between successive checks of node status
      value: 15

  - parameter:
        name: nif_prefix
        description: Prefix to c_lib directory containing NIF libs
        value: |
          "\'.\'"
        erlang_term: "'.'"


  # DISPATCHER
  - parameter:
      name: dispatcher_pool_size
      description: Number of threads used by dispatcher
      value: 1000

  - parameter:
      name: dispatcher_port
      description: Number of port used by dispatcher
      value: 5555

  - parameter:
      name: ranch_timeout
      description: Time in ms after witch ranch kills thread that does nothing
      value: 5000

  - parameter:
      name: dispatcher_timeout
      description: Time in ms after witch ranch answers with error
      value: 2000

  - parameter:
      name: ca_dir
      description: path to dir containing CA and CRL certs used by GSI handler
      value: cacerts


  #CONTROL PANEL
  - parameter:
      name: control_panel_port
      description: Port on which control_panel is available
      value: 8000

  - parameter:
      name: control_panel_static_files_root
      description: Directory in release where static gui files are stored
      value: |
        "\'./gui_static\'"
      erlang_term: "'./gui_static'"

  - parameter:
      name: control_panel_number_of_acceptors
      description: Number of accepting processes in control_panel
      value: 100

  - parameter:
      name: control_panel_max_keepalive
      description: Max time in sec to keep a connection alive
      value: 50


  # DNS
  - parameter:
      name: dns_response_ttl
      description: How long dns response remains valid (in sec)
      value: 60

  - parameter:
      name: dns_tcp_acceptor_pool_size
      description: Number of dns tcp acceptors
      value: 50

  - parameter:
      name: dns_tcp_timeout
      description: Time (in sec) after which dns closes idle connection
      value: 30

  - parameter:
      name: dns_port
      description: DNS port
      value: 53





obsolete:
  - parameter:
      description: |
        Heartbeat management; auto-restarts VM if it dies or becomes unresponsive
        (Disabled by default..use with caution!)
      name: heart
      value: -heart

  - parameter:
      description: Enable kernel poll and a few async threads
      name: kernel_pool_async_threads
      value: |
        +K true
        +A 5

  - parameter:
      description: Tweak GC to run more often
      name: erl_fullsweep_after
      value: -env ERL_FULLSWEEP_AFTER 10
